package:
  name: cropgbm
  version: 1.1.2

source:
  path: /home/xyt/cropgbm_conda/Cropgbm-Conda/

build:
  number: 3
  str: linux64_py3

requirements:
  build:
    - python >=3
    - setuptools
  run:
    - python >=3
    - numpy >=1.20
    - scipy
    - pandas
    - scikit-learn >=0.22
    - lightgbm
    - matplotlib
    - seaborn
    - plink >=1.9

test:
  source_files:
    - run_test.py
    - cropgbm/testdata/*

about:
  home: https://github.com/YuetongXU/CropGBM
  license: MIT
  summary: SNP data preprocessing, population structure analysis, SNP selection, phenotype prediction, and data visualization
  description: Crop Genomic Breeding machine (CropGBM) is a multifunctional program that integrates SNP data preprocessing, population structure analysis, SNP selection, phenotype prediction, and data visualization.
  doc_url: https://ibreeding.github.io/
  dev_url: https://github.com/YuetongXU/CropGBM
